# profiles/tv.conf

# Configuración de Pantalla
RESOLUTION="1280x720"
SCALE="1.0x1.0"
DPI="96"

# Configuración de Audio
# Cambia a true si quieres que el script redireccione el audio a la TV/Sunshine
MANAGE_AUDIO=true
AUDIO_SINK_NAME="Gdev_Virtual_Audio"
